- name: kalliope kodi neuron install
  hosts: localhost
  gather_facts: no
  connection: local
  become: true

  tasks:
    - name: "Kodi Json"
      pip:
        name: kodi-json
        version: 1.0.0
    - name: "Fuzzywuzzy"             
      pip:
        name: fuzzywuzzy
        version: 0.16.0
