- name: kodi neuron
  hosts: localhost
  gather_facts: no
  connection: local
  become: true
  tasks:
    - name: "Dependencies"
      pip:
        name: 
          - kodi-json
          - fuzzywuzzy
        executable: pip3
